[package]
name = "rust_nes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2" # TODO: Update to 2.x
lazy_static = "1.4.0"
rand = "0.8.5"
sdl2 = "0.36.0"
